// app/layout.js (or layout.tsx for TypeScript)
import { ChakraProvider } from '@chakra-ui/react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import ProgressBar from '../components/ProgressBar';
import './globals.css'; // Optional: Global styles
import Head from 'next/head';
//import Router, { usePathname } from 'next/navigation'; 
//import { useEffect } from 'react';


export const metadata = {
  title: 'Real Estate',
  description: 'Real Estate Website',
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <Head>
      <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css' integrity='sha512-42kB9yDlYiCEfx2xVwq0q7hT4uf26FUgSIZBK8uiaEnTdShXjwr8Ip1V4xGJMg3mHkUt9nNuTDxunHF0/EgxLQ==' crossOrigin='anonymous' referrerPolicy='no-referrer' />
      </Head>
      <body>
        <ChakraProvider>
          <ProgressBar/>
          {/* ProgressBar to handle NProgress for route changes */}
          <ProgressBar />
          <header>
            <Navbar />
          </header>
          <main>
            {/* Box from Chakra UI to constrain content width */}
            <div style={{ maxWidth: '1280px', margin: 'auto' }}>
              {children}
            </div>
          </main>
          <footer>
            <Footer />
          </footer>
        </ChakraProvider>
      </body>
    </html>
  );
}



















/*


// app/layout.jsx (or layout.tsx for TypeScript)
import { Box, ChakraProvider } from '@chakra-ui/react';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
//import './globals.css'; // Optional: Global styles

export const metadata = {
  title: 'Real Estate',
  description: 'Real Estate Website',
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <header>
            <Navbar />
          </header>
          <main>
            <Box maxWidth="1280px" m="auto">{children}</Box>
          </main>
          <footer>
            <Footer />
          </footer>
        </ChakraProvider>
      </body>
    </html>
  );
}


*/









/*
import type { Metadata } from "next";
import localFont from "next/font/local";
iport "./globals.css";m

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


*/
